# frozen_string_literal: true

module ElkrbDocs
  # docs/COMPATIBILITY.adoc, rendered from the committed elkjs goldens and
  # the case table in spec/support/golden_cases.rb.
  module CompatibilityPage
    GOLDEN_DIR = File.expand_path("../../spec/fixtures/golden", __dir__)
    DEFAULT_ALGORITHM = "layered"
    COLUMNS = %w[Case Tier Fields Status Reason].freeze

    module_function

    def render
      cases = golden_cases
      [header(cases), *sections(cases)].join("\n")
    end

    def golden_cases
      (GoldenCases::COMPARISON_CASES + [GoldenCases::ERROR_CASE]).map do |kase|
        kase.merge(algorithm: algorithm_of(kase[:name]))
      end
    end

    def algorithm_of(name)
      input = golden_json("inputs/#{name}.json")
      input.dig("graph", "layoutOptions", "elk.algorithm") ||
        DEFAULT_ALGORITHM
    end

    def golden_json(path)
      JSON.parse(File.read(File.join(GOLDEN_DIR, path)))
    end

    def header(cases)
      elkjs = golden_json("MANIFEST.json").fetch("elkjs")
      pending = cases.count { |kase| kase[:pending] }
      <<~ADOC
        = Compatibility with elkjs
        :toc:

        Generated by `rake docs:compatibility` from the goldens in
        `spec/fixtures/golden` and the case table in
        `spec/support/golden_cases.rb`. Do not edit by hand.

        The goldens were produced by elkjs #{elkjs}. Each case lays out one
        input graph with elkrb and compares the result with the golden.
        #{cases.size} cases: #{cases.size - pending} expected to match, #{pending} pending.

        Tier::
        `exact`;; every compared number is within 1e-6 of the golden.
        `structural`;; graph size, each node's own geometry and each edge
        section's endpoints, clipped to the node or port border, are within
        1px.

        Status::
        `match`;; the case is compared at its tier and must match.
        `pending`;; a known gap; the reason names it.

        An error case compares the reason elkrb rejects the graph for, not
        geometry.
      ADOC
    end

    def sections(cases)
      cases.group_by { |kase| kase[:algorithm] }.sort.map do |algorithm, group|
        ["== #{algorithm}\n", table(group)].join("\n")
      end
    end

    def table(group)
      [
        "[cols=\"2,1,2,1,5\",options=\"header\"]",
        "|===",
        COLUMNS.map { |name| "|#{name}" }.join(" "),
        "",
        *group.map { |kase| row(kase) },
        "|===",
        "",
      ].join("\n")
    end

    def row(kase)
      cells = [
        "`#{kase[:name]}`", tier(kase), fields(kase),
        kase[:pending] ? "pending" : "match", kase[:pending]
      ]
      "#{cells.map { |cell| "|#{cell.to_s.gsub('|', '\\|')}" }.join("\n")}\n"
    end

    def tier(kase)
      return kase[:tier] unless error_case?(kase)

      "#{kase[:tier]} (error)"
    end

    def fields(kase)
      return "n/a" if error_case?(kase)

      kase[:fields]&.join(", ") || "all"
    end

    def error_case?(kase)
      kase[:name] == GoldenCases::ERROR_CASE[:name]
    end
  end
end
