# frozen_string_literal: true

module ElkrbDocs
  # docs/OPTIONS.adoc, rendered from Elkrb::Options::Registry.
  module OptionsPage
    HEADER = <<~ADOC
      = Layout options
      :toc:

      Generated by `rake docs:options` from `Elkrb::Options::Registry`.
      Do not edit by hand.

      An option is read from an element's `layoutOptions`, then its
      `properties`, then the options passed to the layout call, then the
      default below. Every alias reaches the same value as the id, and the
      `org.eclipse.elk.` prefix may replace `elk.` on any `elk.` id.

      Status::
      `honoured`;; read as documented.
      `partial`;; read only by some algorithms or from some places; the note
      says which.
      `accepted`;; recognised, but no algorithm acts on it yet; strict mode
      rejects it.

    ADOC

    COLUMNS = %w[
      Id Type Default Status Aliases Algorithms Description Note
    ].freeze

    module_function

    def render
      HEADER + table
    end

    def table
      rows = Elkrb::Options::Registry.all.map { |id, entry| row(id, entry) }
      [
        "[cols=\"3,2,2,1,2,2,3,4\",options=\"header\"]",
        "|===",
        COLUMNS.map { |name| "|#{name}" }.join(" "),
        "",
        *rows,
        "|===",
        "",
      ].join("\n")
    end

    def row(id, entry)
      cells = [
        literal(id), type(entry), default(entry), entry[:status],
        list(entry[:aliases]), algorithms(entry), entry[:description],
        Elkrb::Options::Registry.note(id)
      ]
      "#{cells.map { |cell| "|#{escape(cell)}" }.join("\n")}\n"
    end

    def type(entry)
      return entry[:type].to_s unless entry[:values]

      "#{entry[:type]}: #{list(entry[:values])}"
    end

    def default(entry)
      entry[:default].nil? ? "none" : literal(entry[:default])
    end

    def algorithms(entry)
      entry[:algorithms] == :all ? "all" : list(entry[:algorithms])
    end

    def list(values)
      Array(values).map { |value| literal(value) }.join(", ")
    end

    def literal(value)
      "`+#{value}+`"
    end

    def escape(cell)
      cell.to_s.gsub("|", "\\|")
    end
  end
end
